DROP TABLE IF EXISTS TutoringSession;
DROP TABLE IF EXISTS UserCourse;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS UserBlock;
DROP TABLE IF EXISTS AvailableTimeslot;
DROP TABLE IF EXISTS TutorPreference;
DROP TABLE IF EXISTS LearnerPreference;
DROP TABLE IF EXISTS UserAccount;